# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\nufb_search\x1a\x1cgoogle/protobuf/struct.proto\"\x07\n\x05\x45mpty\"\x1e\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\x89\x02\n\x0eSearchResponse\x12$\n\x03top\x18\x01 \x03(\x0b\x32\x17.google.protobuf.Struct\x12(\n\x07\x61rtists\x18\x02 \x03(\x0b\x32\x17.google.protobuf.Struct\x12\'\n\x06labels\x18\x03 \x03(\x0b\x32\x17.google.protobuf.Struct\x12)\n\x08releases\x18\x04 \x03(\x0b\x32\x17.google.protobuf.Struct\x12\'\n\x06tracks\x18\x05 \x03(\x0b\x32\x17.google.protobuf.Struct\x12*\n\tplaylists\x18\x06 \x03(\x0b\x32\x17.google.protobuf.Struct\"<\n\x10ItemListResponse\x12(\n\x07results\x18\x01 \x03(\x0b\x32\x17.google.protobuf.Struct\"!\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xdf\x02\n\rSearchService\x12?\n\x06Search\x12\x19.ufb_search.SearchRequest\x1a\x1a.ufb_search.SearchResponse\x12H\n\rSearchArtists\x12\x19.ufb_search.SearchRequest\x1a\x1c.ufb_search.ItemListResponse\x12G\n\x0cSearchLabels\x12\x19.ufb_search.SearchRequest\x1a\x1c.ufb_search.ItemListResponse\x12<\n\x0b\x43reateIndex\x12\x11.ufb_search.Empty\x1a\x1a.ufb_search.StatusResponse\x12<\n\x0b\x44\x65leteIndex\x12\x11.ufb_search.Empty\x1a\x1a.ufb_search.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=58
  _globals['_EMPTY']._serialized_end=65
  _globals['_SEARCHREQUEST']._serialized_start=67
  _globals['_SEARCHREQUEST']._serialized_end=97
  _globals['_SEARCHRESPONSE']._serialized_start=100
  _globals['_SEARCHRESPONSE']._serialized_end=365
  _globals['_ITEMLISTRESPONSE']._serialized_start=367
  _globals['_ITEMLISTRESPONSE']._serialized_end=427
  _globals['_STATUSRESPONSE']._serialized_start=429
  _globals['_STATUSRESPONSE']._serialized_end=462
  _globals['_SEARCHSERVICE']._serialized_start=465
  _globals['_SEARCHSERVICE']._serialized_end=816
# @@protoc_insertion_point(module_scope)
