version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.4
  aws-ecr: circleci/aws-ecr@9.8.1
  aws-ecs: circleci/aws-ecs@7.2.2

jobs:
  test:
    docker:
      - image: cimg/python:3.13
    environment:
      IS_LOCAL: true
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pipenv install --dev
      - run:
          name: Lint with flake8
          command: pipenv run lint
      - run:
          name: Lint with black
          command: pipenv run format --check .
      - run:
          name: Lint with isort
          command: pipenv run sort --check-only
      - run:
          name: Mypy type checking
          command: pipenv run mypy
      # - run:
      #     name: Run tests
      #     command: pipenv run tests

  build:
    machine:
      image: ubuntu-2204:2024.01.1
      docker_layer_caching: true
    resource_class: arm.medium
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: "arn:aws:iam::081077757258:role/openid-connect-circleci"
          region: eu-west-2
          profile_name: "OIDC-PROFILE"
          role_session_name: "example-session"
          session_duration: "1800"
      - aws-ecr/build_and_push_image:
          account_id: "081077757258"
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::081077757258:role/openid-connect-circleci
          dockerfile: Dockerfile
          path: .
          region: eu-west-2
          repo: production-ufb-search
          tag: ${CIRCLE_SHA1},latest
          platform: "linux/arm64"

workflows:
  build-and-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - aws-ecs/deploy_service_update:
          requires:
            - build
          auth:
            - aws-cli/setup:
                profile_name: OIDC-PROFILE
                role_arn: arn:aws:iam::081077757258:role/openid-connect-circleci
          cluster: production-ufb
          family: production-ufb-search
          container_image_name_updates: "container=search,tag=latest"
          force_new_deployment: true
          region: eu-west-2
          profile_name: OIDC-PROFILE
