version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.4
  aws-ecr: circleci/aws-ecr@9.8.1
  aws-ecs: circleci/aws-ecs@7.2.2

jobs:
  test:
    docker:
      - image: cimg/python:3.13
    environment:
      IS_LOCAL: true
      OPENSEARCH_DOMAIN_ENDPOINT: "search-logs-abcdefg1234567.us-west-2.es.amazonaws.com"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pipenv install
      - run:
          name: Lint with flake8
          command: pipenv run flake8
      - run:
          name: Lint with black
          command: pipenv run black --check .
      - run:
          name: Lint with isort
          command: pipenv run isort --check-only
      - run:
          name: Mypy type checking
          command: pipenv run mypy
      - run:
          name: Run tests
          command: pipenv run tests

  build-deploy:
    machine:
      image: ubuntu-2204:2024.01.1
      docker_layer_caching: true
    resource_class: arm.medium
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: "arn:aws:iam::081077757258:role/openid-connect-circleci"
          region: eu-west-2
          profile_name: "OIDC-PROFILE"
          role_session_name: "example-session"
          session_duration: "1800"
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-ecr/build_and_push_image:
          account_id: "081077757258"
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::081077757258:role/openid-connect-circleci
          dockerfile: Dockerfile
          path: .
          region: eu-west-2
          repo: production-ufb-search
          tag: ${CIRCLE_SHA1},latest
          platform: "linux/arm64"
      - aws-ecs/update_service:
          cluster: production-ufb
          family: production-ufb-search
          container_image_name_updates: "container=search,tag=${CIRCLE_SHA1}"
          force_new_deployment: false
          region: eu-west-2

workflows:
  deploy:
    jobs:
      - test
      - build-deploy:
          requires:
            - test