version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pipenv install
      - run:
          name: Lint with flake8
          command: pipenv run flake8
      - run:
          name: Lint with black
          command: pipenv run black --check .
      - run:
          name: Lint with isort
          command: pipenv run isort --check-only
      - run:
          name: Mypy type checking
          command: pipenv run mypy

workflows:
  deploy:
    jobs:
      - test